coinjojo/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/coin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include('allauth.urls')),

]

urlpatterns += i18n_patterns(
    path('', include('core.urls')),
    path('', include('user.urls')),
    path('', include('order.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path

from core import views
from core.views import *
from core.utils import *

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('index/<str:sort>/', Index.as_view(), name='index_sorted'),

    path('index/<str:sort_item>/<str:sort_status>/', Index.as_view(), name='index_sorted_item'),
    path('coin-list/<slug>/', coin_list, name='list_sorted_item'),
    path('vote-coin/', vote_coin, name='vote_coin'),

    path('advertising/', advertising, name='advertising'),

    path('add-coin/', AddCoin.as_view(), name='add-coin'),
    path('coin-page/<slug:slug>/', CoinDetail.as_view(), name='coin-page'),
    path('coin-list/<str:filter_by>/', NewlistingList.as_view(), name='coin-list'),
    path('page/<slug>/', page, name='page'),
    path('search/', SearchList.as_view(), name='search'),
    path('coin-category/<slug:slug>/', NewlistingListCategory.as_view(), name='coin-list-category'),
    path('coin-category/<str:sort_item>/<str:sort_status>/<str:slug>', NewlistingListCategory.as_view(), name='category_sorted_item'),
    path('coin-chain/<slug:slug>/', NewlistingListChain.as_view(), name='coin-list-chain'),
    path('coin-chain/<str:sort_item>/<str:sort_status>/<str:slug>', NewlistingListChain.as_view(), name='chain_sorted_item'),
    path('coin-type/<slug:slug>/', NewlistingListType.as_view(), name='coin-list-type'),
    path('coin-type/<str:sort_item>/<str:sort_status>/<str:slug>', NewlistingListType.as_view(), name='type_sorted_item'),
    path('custom_set_language/', custom_set_language, name='custom_set_language'),
    # path('add_like/<int:pk>/', increment_counter, name='add_like')2,

    path('coin-promoted/', NewlistingListPromote.as_view(), name='promote-coin'),
    path('coin-promoted/<str:sort_item>/<str:sort_status>/', NewlistingListPromote.as_view(), name='promote-sort'),

    path('captcha/', captcha_view, name='captcha'),#`1
    path('sort/', get_sort_status_promoted, name='sort'),
    path('sort-promote/', get_sort_status_promote, name='sort-promote'),
    path('sort-list/', get_sort_status_list, name='sort-list'),
    path('sort-profile/', get_sort_status_profile, name='sort-profile'),

    path('search-ajax/', search_coins_ajax, name='search_ajax'),
    path('sort-ajax/', sort_filter_pagination_ajax, name='sort_ajax'),
    path('get_coins_table/', get_coins_table, name='get_coins_table'),

    path('coin-price-history', coin_price_history, name='coin_price_history'),

]

user/urls.py
from django.urls import path

from user.utils import increment_favorite
from user.views import ProfileUser, LikedCoin

app_name = 'user'


urlpatterns = [
    path('profile/<int:pk>/', ProfileUser.as_view(), name='profile'),
    path('account-liked/<int:pk>/', LikedCoin.as_view(), name='account-liked'),
    path('increment_favorite/<int:pk>/', increment_favorite, name='add_favorite'),

    path('account-liked/<int:pk>/<str:sort_item>/<str:sort_status>/', LikedCoin.as_view(), name='account-liked-sort'),

]

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
	vote_coins = models.ManyToManyField('core.Coin', verbose_name='Голоса за коины', blank=True)
	vote_count = models.IntegerField('Количество голосов', default=5)
	first_vote = models.DateTimeField(null=True, blank=True, verbose_name='Дата первого голоса')

user/views.py
from django.db.models import Count, Q
from django.http import Http404
from django.views.generic import ListView

from core.models import Page, OrderItem, Cart, Coin, CreateOrder, CartCold, Listing, Order
from core.views import get_sorted_mixin


class ProfileUser(ListView):
    template_name = 'account-profile.html'

    def get_queryset(self):
        return OrderItem.objects.filter(cart__user=self.kwargs['pk'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProfileUser, self).get_context_data(**kwargs)
        context['page'] = Page.objects.get(slug='profile')
        context['orders'] = Order.objects.filter(user__pk=self.kwargs['pk']).select_related('coin')
        return context


class LikedCoin(ListView):
    paginate_by = 6
    template_name = 'account-liked-coins.html'
    model = Page

    # def get_queryset(self):
    #     sort = self.kwargs.get('sort')
    #     sort_item = self.kwargs.get('sort_item')
    #     sort_status = self.kwargs.get('sort_status')
    #     user = self.request.user
    #     if user.is_authenticated and (user.pk == self.kwargs['pk']):
    #         return get_sorted_mixin(sort_item, sort_status, sort, profile=True)
    #     raise Http404

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(LikedCoin, self).get_context_data(**kwargs)
        context['page'] = Page.objects.get(slug='like-coin')
        context['listing'] = Listing.objects.get(slug='all-coins')
        context['coins'] = context['listing'].get_coins().filter(favorite__in=[self.request.user])
        context['is_profile'] = True
        return context

user/templates/account-liked-coins.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}
    <title>{{ page.title_seo }}</title>
{% endblock %}

{% block description %}
    <meta name="description" content="{{ page.description_seo }}">
{% endblock %}

{% block head %}
    <meta property="og:title" content="{% if page.title %}{{ page.title|striptags|truncatechars:50 }}{% endif %}"/>
    <meta property="og:description"
          content="{% if page.description %}{{ page.description|striptags|truncatechars:160 }}{% endif %}"/>
    <meta property="og:image" content="{% if page.image_url %}{{ page.image_url.url }}{% endif %}"/>
    <meta property="og:image:width" content="1200"/>
    <meta property="og:image:height" content="630"/>
    <meta property="og:url" content="{{ request.build_absolute_uri }}"/>
    <meta property="og:site_name" content="CoinYoYo"/>
    <meta property="og:type" content="website"/>
    <meta name="twitter:card" content="summary_large_image"/>
{% endblock %}

{% load static %}
{% block content %}
    <main class="main">
        <section class="account">
            <div class="hero-banner hero-banner-profile container">
                <div class="hero-banner__bg">
                    <picture class="hero__bg-picture-dark">
                        <source data-srcset="{% static 'img/index/hero/bg.webp' %}" type="image/webp"
                                media="(min-width: 550px)">
                        <source data-srcset="{% static 'img/index/hero/bg-mob-2.webp' %}" type="image/webp">
                        <img data-src="{% static 'img/index/hero/bg.png' %}" alt="" width="0" height="0" class="lazy">
                    </picture>
                    <picture class="hero__bg-picture-light">
                        <source data-srcset="{% static 'img/index/hero/bg-light.webp' %}" type="image/webp"
                                media="(min-width: 550px)">
                        <source data-srcset="{% static 'img/index/hero/bg-light.webp' %}" type="image/webp">
                        <img data-src="{% static 'img/index/hero/bg-light.png' %}" alt="" width="0" height="0"
                             class="lazy">
                    </picture>
                </div>
                <div class="hero-banner__header">
                    <div class="hero-banner__page-address page-address">
                        <ul>
                            <li>
                                <a href="{% url 'core:index' %}">
                                    {% trans "Home" %}
                                </a>
                            </li>
                            <li>
                                <svg width="16" height="16" viewBox="0 0 16 16">
                                    <use xlink:href="{% static 'img/sprites.svg#arrow-next' %}"></use>
                                </svg>
                            </li>
                            <li>
                                <a href="#">
                                    {% trans "Liked Coin" %}
                                </a>
                            </li>
                        </ul>
                    </div>
                    <a href="#" class="hero-banner__btn visible-on-tablet">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none">
                            <path fill="#C8C9CA" fill-rule="evenodd"
                                  d="M9.707 2.409C9 3.036 9 4.183 9 6.476v11.048c0 2.293 0 3.44.707 4.067.707.627 1.788.439 3.95.062l2.33-.406c2.394-.418 3.591-.627 4.302-1.505.711-.879.711-2.149.711-4.69V8.948c0-2.54 0-3.81-.71-4.689-.712-.878-1.91-1.087-4.304-1.504l-2.328-.407c-2.162-.377-3.243-.565-3.95.062ZM12 10.169c.414 0 .75.351.75.784v2.094c0 .433-.336.784-.75.784s-.75-.351-.75-.784v-2.094c0-.433.336-.784.75-.784Z"
                                  clip-rule="evenodd"/>
                            <path fill="#C8C9CA"
                                  d="M7.547 4.5c-2.058.003-3.131.048-3.815.732C3 5.964 3 7.142 3 9.5v5c0 2.357 0 3.535.732 4.268.684.683 1.757.729 3.815.732-.047-.624-.047-1.344-.047-2.123V6.623c0-.78 0-1.5.047-2.123Z"/>
                        </svg>
                        {% trans "Log out" %}
                    </a>
                </div>
                <div class="hero-banner__title-wrapper">
                    <h1 class="hero-banner__title title">
                        {% trans "My account" %}
                    </h1>
                    <h2 class="account-username">{{ user.username }}</h2>
                </div>
                <nav class="hero-banner__nav">
                    <ul>
                        <li>
                            <a href="{% url 'user:account-liked' pk=user.pk %}" class="current">
                                <img src="{% static 'img/icons/dollar.svg' %}" width="24" height="24" loading="lazy"
                                     alt="">
                                {% trans "Liked coins" %}
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'user:profile' pk=user.pk %}">
                                <img src="{% static 'img/icons/profile.svg' %}" width="24" height="24" loading="lazy"
                                     alt="">
                                {% trans "Profile" %}
                            </a>
                        </li>
                        <li class="hide-on-tablet">
                            <a href="{% url 'account_logout' %}" class="hide-on-tablet">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none">
                                    <path fill="#C8C9CA" fill-rule="evenodd"
                                          d="M9.707 2.409C9 3.036 9 4.183 9 6.476v11.048c0 2.293 0 3.44.707 4.067.707.627 1.788.439 3.95.062l2.33-.406c2.394-.418 3.591-.627 4.302-1.505.711-.879.711-2.149.711-4.69V8.948c0-2.54 0-3.81-.71-4.689-.712-.878-1.91-1.087-4.304-1.504l-2.328-.407c-2.162-.377-3.243-.565-3.95.062ZM12 10.169c.414 0 .75.351.75.784v2.094c0 .433-.336.784-.75.784s-.75-.351-.75-.784v-2.094c0-.433.336-.784.75-.784Z"
                                          clip-rule="evenodd"/>
                                    <path fill="#C8C9CA"
                                          d="M7.547 4.5c-2.058.003-3.131.048-3.815.732C3 5.964 3 7.142 3 9.5v5c0 2.357 0 3.535.732 4.268.684.683 1.757.729 3.815.732-.047-.624-.047-1.344-.047-2.123V6.623c0-.78 0-1.5.047-2.123Z"/>
                                </svg>
                                {% trans "Log out" %}
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            {% include 'include/full_coin_table.html' %}
        </section>
    </main>

{% endblock %}

user/templates/account-profile.html
{% extends 'base.html' %}

{% load i18n %}
{% load l10n %}
{% load humanize %}

{% block title %}
    <title>{{ page.title_seo }}</title>
{% endblock %}

{% block description %}
    <meta name="description" content="{{ page.description_seo }}">
{% endblock %}

{% block head %}
    <meta property="og:title" content="{% if page.title %}{{ page.title|striptags|truncatechars:50 }}{% endif %}"/>
    <meta property="og:description"
          content="{% if page.description %}{{ page.description|striptags|truncatechars:160 }}{% endif %}"/>
    <meta property="og:image" content="{% if page.image_url %}{{ page.image_url.url }}{% endif %}"/>
    <meta property="og:image:width" content="1200"/>
    <meta property="og:image:height" content="630"/>
    <meta property="og:url" content="{{ request.build_absolute_uri }}"/>
    <meta property="og:site_name" content="CoinYoYo"/>
    <meta property="og:type" content="website"/>
    <meta name="twitter:card" content="summary_large_image"/>

    <!-- JSON-LD Structured Data for BreadcrumbList -->
    <script type="application/ld+json">
        {
          "@context": "https://schema.org",
          "@type": "BreadcrumbList",
          "itemListElement": [
            {
              "@type": "ListItem",
              "position": 1,
              "name": "{% trans 'Home' %}",
              "item": "{{ request.scheme }}://{{ request.get_host }}{% url 'core:index' %}"
            },
            {
              "@type": "ListItem",
              "position": 2,
              "name": "{% trans 'Profile' %}",
              "item": "{{ request.build_absolute_uri }}"
            }
          ]
        }
    </script>
{% endblock %}

{% load static %}
{% block content %}

    <main class="main">
        <section class="account">
            <div class="hero-banner hero-banner-profile container">
                <div class="hero-banner__bg">
                    <picture class="hero__bg-picture-dark">
                        <source data-srcset="{% static 'img/index/hero/bg.webp' %}" type="image/webp"
                                media="(min-width: 550px)">
                        <source data-srcset="{% static 'img/index/hero/bg-mob-2.webp' %}" type="image/webp">
                        <img data-src="{% static 'img/index/hero/bg.png' %}" alt="" width="0" height="0" class="lazy">
                    </picture>
                    <picture class="hero__bg-picture-light">
                        <source data-srcset="{% static 'img/index/hero/bg-light.webp' %}" type="image/webp"
                                media="(min-width: 550px)">
                        <source data-srcset="{% static 'img/index/hero/bg-light.webp' %}" type="image/webp">
                        <img data-src="{% static 'img/index/hero/bg-light.png' %}" alt="" width="0" height="0"
                             class="lazy">
                    </picture>
                </div>
                <div class="hero-banner__header">
                    <div class="hero-banner__page-address page-address">
                        <ul>
                            <li>
                                <a href="{% url 'core:index' %}">
                                    {% trans "Home" %}
                                </a>
                            </li>
                            <li>
                                <svg width="16" height="16" viewBox="0 0 16 16">
                                    <use xlink:href="{% static 'img/sprites.svg' %}#arrow-next"></use>
                                </svg>
                            </li>
                            <li>
                                <a href="#">
                                    {% trans "Profile" %}
                                </a>
                            </li>
                        </ul>
                    </div>
                    <a href="{% url 'account_logout' %}" class="hero-banner__btn visible-on-tablet">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none">
                            <path fill="#C8C9CA" fill-rule="evenodd"
                                  d="M9.707 2.409C9 3.036 9 4.183 9 6.476v11.048c0 2.293 0 3.44.707 4.067.707.627 1.788.439 3.95.062l2.33-.406c2.394-.418 3.591-.627 4.302-1.505.711-.879.711-2.149.711-4.69V8.948c0-2.54 0-3.81-.71-4.689-.712-.878-1.91-1.087-4.304-1.504l-2.328-.407c-2.162-.377-3.243-.565-3.95.062ZM12 10.169c.414 0 .75.351.75.784v2.094c0 .433-.336.784-.75.784s-.75-.351-.75-.784v-2.094c0-.433.336-.784.75-.784Z"
                                  clip-rule="evenodd"/>
                            <path fill="#C8C9CA"
                                  d="M7.547 4.5c-2.058.003-3.131.048-3.815.732C3 5.964 3 7.142 3 9.5v5c0 2.357 0 3.535.732 4.268.684.683 1.757.729 3.815.732-.047-.624-.047-1.344-.047-2.123V6.623c0-.78 0-1.5.047-2.123Z"/>
                        </svg>
                        {% trans "Log out" %}
                    </a>
                </div>
                <div class="hero-banner__title-wrapper">
                    <h1 class="hero-banner__title title">
                        {% trans "My account" %}
                    </h1>
                    <h2 class="account-username">{{ user.username }}</h2>
                </div>
                <nav class="hero-banner__nav">
                    <ul>
                        <li>
                            <a href="{% url 'user:account-liked' pk=user.pk %}">
                                <img src="{% static 'img/icons/dollar.svg' %}" width="24" height="24" loading="lazy"
                                     alt="">
                                {% trans "Liked coins" %}
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'user:profile' pk=user.pk %}" class="current">
                                <img src="{% static 'img/icons/profile.svg' %}" width="24" height="24" loading="lazy"
                                     alt="">
                                {% trans "Profile" %}
                            </a>
                        </li>
                        <li class="hide-on-tablet">
                            <a href="{% url 'account_logout' %}" class="hide-on-tablet">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none">
                                    <path fill="#C8C9CA" fill-rule="evenodd"
                                          d="M9.707 2.409C9 3.036 9 4.183 9 6.476v11.048c0 2.293 0 3.44.707 4.067.707.627 1.788.439 3.95.062l2.33-.406c2.394-.418 3.591-.627 4.302-1.505.711-.879.711-2.149.711-4.69V8.948c0-2.54 0-3.81-.71-4.689-.712-.878-1.91-1.087-4.304-1.504l-2.328-.407c-2.162-.377-3.243-.565-3.95.062ZM12 10.169c.414 0 .75.351.75.784v2.094c0 .433-.336.784-.75.784s-.75-.351-.75-.784v-2.094c0-.433.336-.784.75-.784Z"
                                          clip-rule="evenodd"/>
                                    <path fill="#C8C9CA"
                                          d="M7.547 4.5c-2.058.003-3.131.048-3.815.732C3 5.964 3 7.142 3 9.5v5c0 2.357 0 3.535.732 4.268.684.683 1.757.729 3.815.732-.047-.624-.047-1.344-.047-2.123V6.623c0-.78 0-1.5.047-2.123Z"/>
                                </svg>
                                {% trans "Log out" %}
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="account__container container">
                <div class="account__profile-table">
                    <div class="account__profile-table--wrapper scroll-wrapper">
                        <table>
                            <colgroup>
                                <col>
                                <col>
                                <col>
                                <col>
                                <col>
                            </colgroup>
                            <thead>
                            <tr>
                                <th>
                                    {% trans "Coin" %}
                                </th>
                                <th>
                                    {% trans "Link usage" %}
                                </th>
                                <th>
                                    {% trans "Start at" %}
                                </th>
                                <th>
                                    {% trans "Finish at" %}
                                </th>
                                <th>
                                    {% trans "Type" %}
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for order in orders %}
                                <tr>
                                    <td>
                                        <div class="account__table-coin">
                                            <div class="account__table-coin--logo">
                                                <picture>
                                                    <source srcset="{{ order.coin.photo_coin.url }}" type="image/webp">
                                                    <img src="{{ order.coin.photo_coin.url }}" alt="" width="32"
                                                         height="32"
                                                         loading="lazy">
                                                </picture>
                                            </div>
                                            <a href="{{ order.coin.get_absolute_url }}"><b
                                                    class="account__table-coin--name">
                                                {{ order.coin.coin_name }}</b></a>
                                            <span class="account__table-coin--abbreviation">{{ order.coin.coin_symbol }}</span>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="account-table-td-h">
                                            {% trans "Link usage" %}
                                        </div>
                                        <div>
                                            {{ order.coin.counter_link_usage }}
                                        </div>
                                    </td>
                                    <td>
                                        <div class="account-table-td-h">
                                            {% trans "Start at" %}
                                        </div>
                                        <div>
                                            {{ order.start_at|date:"d F Y" }}
                                        </div>
                                    </td>
                                    <td>
                                        <div class="account-table-td-h">
                                            {% trans "Finish at" %}
                                        </div>
                                        <div>
                                            {{ order.finish_at|date:"d F Y" }}
                                        </div>
                                    </td>
                                    <td>
                                        <div class="account-table-td-h">
                                            {% trans "Type" %}
                                        </div>
                                        <div>
                                            {{ order.type }}
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="account__footer table-footer">
                    {% if is_paginated %}
                        <div class="table-footer__pagination pagination hide-on-tablet">
                            {% if page_obj.has_previous %}
                                <a href="?page={{ page_obj.previous_page_number }}" class="pagination__arrow _prev"
                                   title="Prev">
                                    <svg width="16" height="16" viewBox="0 0 16 16">
                                        <use xlink:href="{% static 'img/sprites.svg' %}#arrow-prev"></use>
                                    </svg>
                                </a>
                            {% endif %}
                            <div class="pagination__list">
                                {% for p in page_obj.paginator.page_range %}
                                    <a href="?page={{ p }}">
                                        {{ p }}
                                    </a>
                                {% endfor %}
                            </div>
                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}  " class="pagination__arrow _next"
                                   title="Next">
                                    <svg width="16" height="16" viewBox="0 0 16 16">
                                        <use xlink:href="{% static 'img/sprites.svg' %}#arrow-next"></use>
                                    </svg>
                                </a>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </section>
    </main>

{% endblock %}