coinjojo/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/coin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include('allauth.urls')),

]

urlpatterns += i18n_patterns(
    path('', include('core.urls')),
    path('', include('user.urls')),
    path('', include('order.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path

from core import views
from core.views import *
from core.utils import *

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('index/<str:sort>/', Index.as_view(), name='index_sorted'),

    path('index/<str:sort_item>/<str:sort_status>/', Index.as_view(), name='index_sorted_item'),
    path('coin-list/<slug>/', coin_list, name='list_sorted_item'),
    path('vote-coin/', vote_coin, name='vote_coin'),

    path('advertising/', advertising, name='advertising'),

    path('add-coin/', AddCoin.as_view(), name='add-coin'),
    path('coin-page/<slug:slug>/', CoinDetail.as_view(), name='coin-page'),
    path('coin-list/<str:filter_by>/', NewlistingList.as_view(), name='coin-list'),
    path('page/<slug>/', page, name='page'),
    path('search/', SearchList.as_view(), name='search'),
    path('coin-category/<slug:slug>/', NewlistingListCategory.as_view(), name='coin-list-category'),
    path('coin-category/<str:sort_item>/<str:sort_status>/<str:slug>', NewlistingListCategory.as_view(), name='category_sorted_item'),
    path('coin-chain/<slug:slug>/', NewlistingListChain.as_view(), name='coin-list-chain'),
    path('coin-chain/<str:sort_item>/<str:sort_status>/<str:slug>', NewlistingListChain.as_view(), name='chain_sorted_item'),
    path('coin-type/<slug:slug>/', NewlistingListType.as_view(), name='coin-list-type'),
    path('coin-type/<str:sort_item>/<str:sort_status>/<str:slug>', NewlistingListType.as_view(), name='type_sorted_item'),
    path('custom_set_language/', custom_set_language, name='custom_set_language'),
    # path('add_like/<int:pk>/', increment_counter, name='add_like')2,

    path('coin-promoted/', NewlistingListPromote.as_view(), name='promote-coin'),
    path('coin-promoted/<str:sort_item>/<str:sort_status>/', NewlistingListPromote.as_view(), name='promote-sort'),

    path('captcha/', captcha_view, name='captcha'),#`1
    path('sort/', get_sort_status_promoted, name='sort'),
    path('sort-promote/', get_sort_status_promote, name='sort-promote'),
    path('sort-list/', get_sort_status_list, name='sort-list'),
    path('sort-profile/', get_sort_status_profile, name='sort-profile'),

    path('search-ajax/', search_coins_ajax, name='search_ajax'),
    path('sort-ajax/', sort_filter_pagination_ajax, name='sort_ajax'),
    path('get_coins_table/', get_coins_table, name='get_coins_table'),

    path('coin-price-history', coin_price_history, name='coin_price_history'),

]

user/urls.py
from django.urls import path

from user.utils import increment_favorite
from user.views import ProfileUser, LikedCoin

app_name = 'user'


urlpatterns = [
    path('profile/<int:pk>/', ProfileUser.as_view(), name='profile'),
    path('account-liked/<int:pk>/', LikedCoin.as_view(), name='account-liked'),
    path('increment_favorite/<int:pk>/', increment_favorite, name='add_favorite'),

    path('account-liked/<int:pk>/<str:sort_item>/<str:sort_status>/', LikedCoin.as_view(), name='account-liked-sort'),

]

core/forms.py
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Invisible, ReCaptchaV2Checkbox
from django.forms import ModelForm
from django import forms
from core.models import *


class CreateCoin(ModelForm):
    class Meta:
        model = Coin
        fields = "__all__"
        exclude = ['votes', 'votes_today', 'website_url']


class AddItem(ModelForm):
    class Meta:
        model = OrderItem
        fields = ['date', 'coin', 'type']


class OrderForm(ModelForm):
    class Meta:
        model = CreateOrder
        fields = "__all__"


class CaptchaForm(forms.Form):
    captcha = ReCaptchaField(
        widget=ReCaptchaV2Checkbox(
            attrs={'theme': 'dark'}
        )
    )
    coin_pk = forms.IntegerField()


class SortForm(forms.Form):
    sort = forms.CharField()

core/views.py
import os
from datetime import datetime, timedelta

import requests
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.utils import timezone
from django.db.models import Count, Q, When, Case, BooleanField

from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, DetailView, ListView
from dotenv import load_dotenv

from core.forms import CreateCoin, CaptchaForm
from core.models import Coin, Category, NetworkChain, ListingPlatform, Page, Type, Social, Listing, AdvertisingItem, \
    Banner, ReferenceCurrency
from core.utils import increment_metrik, increment_counter, get_text_by_number, convert_period_to_days

load_dotenv()


def page(request, slug):
    context = {
        'page': Page.objects.get(slug=slug)
    }
    return render(request, 'privacy-police.html', context=context)


def coin_list(request, slug):
    listing = Listing.objects.get(slug=slug)
    coins = listing.get_coins()

    is_paginated = True
    disable_filter = False
    if listing.filter_by == 'new' or listing.filter_by == 'promote':
        coins = coins[:30]
        is_paginated = False
        disable_filter = True
    else:
        p = Paginator(coins, 30)
        page_num = request.GET.get('page', 1)
        coins = p.page(page_num)

    context = {
        'listing': listing,
        'coins': coins,
        'is_paginated': is_paginated,
        'page': Page.objects.get(slug='coin-list'),
        'categories': Category.objects.filter(draft=False),
        'chains': NetworkChain.objects.filter(draft=False),
        'types': Type.objects.all(),
        'disable_filter': disable_filter,
    }
    return render(request, 'new-listing.html', context=context)


def get_coins_table(request):
    listing = Listing.objects.get(slug=request.GET.get('listing_slug'))
    coins = listing.get_coins()

    category = request.GET.get('category', 'all')
    network_chain = request.GET.get('network_chain', 'all')
    type_project = request.GET.get('type_project', 'all')

    if category != 'all':
        category = Category.objects.get(slug=category)
        coins = coins.filter(category=category)
    if network_chain != 'all':
        network_chain = NetworkChain.objects.get(slug=network_chain)
        coins = coins.filter(network_chain=network_chain)
    if type_project != 'all':
        type_project = Type.objects.get(slug=type_project)
        coins = coins.filter(type_project=type_project)

    sort_direction = request.GET.get('sort_direction')
    sort_name = request.GET.get('sort_name')

    sort = []
    if sort_name == 'votes' and listing.filter_by == 'best_today':
        sort_name = "votes_today"
    if sort_name == 'votes_today' and listing.filter_by == 'best_all':
        sort_name = "votes"

    if sort_direction == 'asc':
        sort.append(f'-{sort_name}')
    if sort_direction == 'desc':
        sort.append(f'{sort_name}')

    coins = coins.order_by(*sort)

    p = Paginator(coins, 30)
    page_num = request.GET.get('page', 1)
    page = p.page(page_num)

    context = {
        'coins': page,
        "listing": listing,
    }

    pagination = None
    if request.GET.get('is_paginated'):
        pagination = render(request, 'include/pagination.html', context={'page_obj': page, "listing": listing}).content.decode("utf-8")

    return JsonResponse({
        'table': render(request, 'include/coin_table.html', context=context).content.decode("utf-8"),
        'pagination': pagination})


def index(request):
    context = {
        'page': Page.objects.get(slug='index'),
        'promoted_listing': Listing.objects.get(slug='promoted'),
        'best_listing': Listing.objects.get(slug='today-s-best'),
    }

    banners = Banner.objects.filter(location__startswith='index', show=True)
    context['banner_under_header'] = banners.filter(location='index_under_header').last()

    total_crypto = [coin for coin in Coin.objects.all()]
    total_trading = [coin.market_cap for coin in total_crypto]
    context['total_trading'] = 0
    for value in total_trading:
        if value:
            context['total_trading'] += value
    context['total_trading'] = get_text_by_number(context['total_trading'])

    total_vote = [coin.votes for coin in total_crypto]
    context['total_votes'] = int(sum(total_vote))
    context['total_currencies'] = len(total_crypto)

    context['new_listing_coin'] = Listing.objects.get(slug="new-listings").get_coins()[:4]
    context['top_today_coin'] = Listing.objects.get(slug="today-s-best").get_coins()[:4]
    context['top_all_time'] = Listing.objects.get(slug="all-time-best").get_coins()[:4]
    context['disable_filter'] = True
    return render(request, 'index.html', context=context)


def vote_coin(request):
    user = request.user
    coin = Coin.objects.get(id=request.GET.get('coin'))

    if not user.is_authenticated:
        return JsonResponse({'status': False})

    if coin not in user.vote_coins.all():
        if user.vote_count <= 0:
            return JsonResponse({'status': False})

        coin.votes += 1
        coin.votes_today += 1
        coin.save()

        user.vote_coins.add(coin)
        user.vote_count -= 1
        if not user.first_vote:
            user.first_vote = timezone.now()
        user.save()
        return JsonResponse({'status': True})

    return JsonResponse({'status': False})


def advertising(request):
    if request.method == 'POST':
        name = request.POST.get('advertising_name')
        email = request.POST.get('advertising_email')
        question = request.POST.get('advertising_question')

        new_item = AdvertisingItem(name=name, email=email, question=question)
        new_item.save()

    return JsonResponse({"status": "success"})


class Index(TemplateView):
    template_name = 'index.html'
    context_object_name = 'coins'

    def get_context_data(self, *, object_list=None, **kwargs):
        today = timezone.now().date()
        context = super(Index, self).get_context_data(**kwargs)

        context['new_listing_coin'] = Coin.objects.filter(is_moderate=True).order_by('-publish_date')[:4]
        context['top_today_coin'] = Coin.objects.filter(is_moderate=True).annotate(counter_like=Count('vote'),
                                                                                   counter_like_today=Count('vote',
                                                                                                            filter=Q(
                                                                                                                vote__date_new__date=today))).order_by(
            '-counter_like_today')[:4]
        context['top_all_time'] = Coin.objects.filter(is_moderate=True).annotate(counter_like=Count('vote'),
                                                                                 counter_like_today=Count('vote',
                                                                                                          filter=Q(
                                                                                                              vote__date_new__date=today))).order_by(
            '-counter_like')[:4]
        context['coin_counter'] = len(Coin.objects.filter(is_moderate=True))
        context['page'] = Page.objects.get(slug='index')
        context['categories'] = Category.objects.filter(draft=False)
        context['chains'] = NetworkChain.objects.filter(draft=False)
        context['types'] = Type.objects.all()
        total_trading = [coin.market_cap for coin in Coin.objects.all()]
        total_vote = [vote for vote in Vote.objects.all()]
        total_crypto = [coin for coin in Coin.objects.all()]
        total_user = [User for User in User.objects.all()]
        context['total_trading'] = int(sum(total_trading))
        context['total_vote'] = len(total_vote)
        context['total_crypto'] = len(total_crypto)
        context['total_user'] = len(total_user)

        if self.kwargs.get('sort') != 'all_time':
            context['today'] = True
            context['name_filter'] = "Todays's Best"
        else:
            context['all_time'] = True
            context['name_filter'] = 'All Time Best'

        context['socials'] = Social.objects.all()
        context['promoted_coins'] = filter_coins(filter_by='promote')
        context['coins'] = filter_coins(filter_by='best_today')
        return context


class AddCoin(CreateView):
    template_name = 'add-coin.html'
    form_class = CreateCoin
    model = Coin
    success_url = reverse_lazy('core:index')

    def post(self, request, *args, **kwargs):
        data = request.POST.copy()
        files = request.FILES

        if data.get('network_chain') == 'other':
            if data.get('network_chain_other'):
                network_chain = NetworkChain.objects.create(name=data.get('network_chain_other'))
                data['network_chain'] = network_chain.pk
            else:
                data['network_chain'] = None

        if data.get('category') == 'other':
            if data.get('category_other'):
                category = Category.objects.create(name=data.get('category_other'))
                data['category'] = category.pk
            else:
                data['category'] = None

        if data.get('listing_platform') == 'other':
            if data.get('listing_platform_other'):
                listing_platform = ListingPlatform.objects.create(name=data.get('listing_platform_other'))
                data['listing_platform'] = listing_platform.pk
            else:
                data['listing_platform'] = None

        form = self.form_class(data, files)

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save()
        return JsonResponse({'status': 'success'})

core/templates/_table-coins-item_1.html
{% load static %}
{% load poll_extras %}
{% load i18n %}
{% load humanize %}
{% for coin in coins %}
<tr>
    <td>
        <span class="table-coins__number"></span>
    </td>
    <td>
        <div class="table-coins__coin">
            <div class="table-coins__coin--avatar">
                <picture>
                    <source srcset="{{ coin.photo_coin.url }}" type="image/webp">
                    <img src="{{ coin.photo_coin.url }}" alt="" width="32" height="32" loading="lazy">
                </picture>
            </div>
            <a href="{{ coin.get_absolute_url }}"><h3 class="table-coins__coin--name">{{ coin.coin_name }}</h3></a>
            <span class="table-coins__coin--abbreviation">{{ coin.coin_symbol }}</span>
        </div>
    </td>
    <td>
        {{ coin.category.name }}
    </td>
    <td>
		<span class="table-coins__chain">
			<img src="{{ coin.network_chain.photo.url }}" width="20" height="20" alt="">
			<b>{{ coin.network_chain.name }}</b>
		</span>
    </td>
    <td> {% if coin.price_24h > 0 %}
        <b class="table-coins__value grow-value">
            <svg width="16" height="16" viewBox="0 0 16 16">
                <use xlink:href="{% static 'img/sprites.svg' %}#arrow-grow"></use>
            </svg>
            {{ coin.price_24h }}
        </b>
        {% else %}
        <b class="table-coins__value danger-value">
            <svg width="16" height="16" viewBox="0 0 16 16">
                <use xlink:href="{% static 'img/sprites.svg' %}#arrow-drop"></use>
            </svg>
            {{ coin.price_24h }}
        </b>
        {% endif %}
    </td>
    <td>
        ${{ coin.market_cap|normalize_amount }}
    </td>
    <td>
        ${{ coin.price|normalize_amount }}
    </td>
    <td>
        7 July
    </td>
    <td>

    </td>
    <td>
        <a href="#authorization-popup-2" class="vote-btn btn open-popup" type="button" data-coin-pk="{{ coin.pk }}">
			<svg width="10" height="14" viewBox="0 0 10 14">
				<use xlink:href="{% static 'img/sprites.svg' %}#arrow-to-up"></use>
			</svg>
            {{ coin.counter_like }}
		</a>
	</td>
    {% if user in coin.favorite.all %}
    <td>
        <form action="{% url 'user:add_favorite' pk=coin.pk %}" method="GET">
             <input type="hidden" name="previous_page" value="{{ request.path }}">
            <button class="table-coins__favorite favorite-btn _active" title="Add to favorite" type="submit">
                <svg width="20" height="20" viewBox="0 0 20 20">
                    <use xlink:href="{% static 'img/sprites.svg' %}#star"></use>
                </svg>
            </button>
        </form>
    </td>
    {% else %}
    <td>
        <form action="{% url 'user:add_favorite' pk=coin.pk %}" method="GET">
             <input type="hidden" name="previous_page" value="{{ request.path }}">
            <button class="table-coins__favorite favorite-btn" title="Add to favorite" type="submit">
                <svg width="20" height="20" viewBox="0 0 20 20">
                    <use xlink:href="{% static 'img/sprites.svg' %}#star"></use>
                </svg>
            </button>
        </form>
    </td>
    {% endif %}
</tr>
{% endfor %}

core/templates/new-listing.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}
    <title>{{ listing.title_seo }}</title>
{% endblock %}

{% block description %}
    <meta name="description" content="{{ listing.description_seo }}">
{% endblock %}

{% block head %}
    <meta property="og:title" content="{% if page.title %}{{ page.title|striptags|truncatechars:50 }}{% endif %}"/>
    <meta property="og:description"
          content="{% if page.description %}{{ page.description|striptags|truncatechars:160 }}{% endif %}"/>
    <meta property="og:image" content="{% if page.image_url %}{{ page.image_url.url }}{% endif %}"/>
    <meta property="og:image:width" content="1200"/>
    <meta property="og:image:height" content="630"/>
    <meta property="og:url" content="{{ request.build_absolute_uri }}"/>
    <meta property="og:site_name" content="CoinYoYo"/>
    <meta property="og:type" content="website"/>
    <meta name="twitter:card" content="summary_large_image"/>

    <!-- JSON-LD Structured Data for BreadcrumbList -->
    <script type="application/ld+json">
        {
          "@context": "https://schema.org",
          "@type": "BreadcrumbList",
          "itemListElement": [
            {
              "@type": "ListItem",
              "position": 1,
              "name": "{% trans 'Home' %}",
              "item": "{{ request.scheme }}://{{ request.get_host }}{% url 'core:index' %}"
            },
            {
              "@type": "ListItem",
              "position": 2,
              "name": "{% trans 'New listings' %}",
              "item": "{{ request.build_absolute_uri }}"
            }
          ]
        }
    </script>

{% endblock %}

{% load static %}
{% block content %}
    <main class="main">
        <section class="hero container">
            <div class="hero__page-address page-address">
                <ul>
                    <li>
                        <a href="{% url 'core:index' %}">
                            {% trans "Home" %}
                        </a>
                    </li>
                    <li>
                        <svg width="16" height="16" viewBox="0 0 16 16">
                            <use xlink:href="{% static 'img/sprites.svg#arrow-next' %}"></use>
                        </svg>
                    </li>
                    <li>
                        <a href="#">
                            {% trans "Coin List" %}
                        </a>
                    </li>
                </ul>
            </div>
            <div class="hero__bg" aria-hidden="true">
                <picture class="hero__bg-picture-dark">
                    <source data-srcset="{% static 'img/index/hero/bg.webp' %}" type="image/webp"
                            media="(min-width: 550px)">
                    <source data-srcset="{% static 'img/index/hero/bg-mob-2.webp' %}" type="image/webp">
                    <img data-src="{% static 'img/index/hero/bg.png' %}" alt="" width="0" height="0" class="lazy">
                </picture>
                <picture class="hero__bg-picture-light">
                    <source data-srcset="{% static 'img/index/hero/bg-light.webp' %}" type="image/webp"
                            media="(min-width: 550px)">
                    <source data-srcset="{% static 'img/index/hero/bg-light.webp' %}" type="image/webp">
                    <img data-src="{% static 'img/index/hero/bg-light.png' %}" alt="" width="0" height="0" class="lazy">
                </picture>
            </div>
{#            <h1 class="hero__title main-title">#}
{#                {{ page.title }}#}
{#            </h1>#}
            <div class="hero__text">
                <p>
                    {{ page.description|safe }}
                </p>
            </div>
            <div class="hero__image" style="padding-top: 28%;">
                <div class="hero__image--item">
                    <picture>
                        <source data-srcset="{% static 'img/index/hero/cursor.webp' %}" type="image/webp">
                        <img class="lazy" data-src="{% static 'img/index/hero/cursor.png' %}" alt="" width="65"
                             height="65">
                    </picture>
                </div>
                <div class="hero__image--item">
                    <picture>
                        <source data-srcset="{% static 'img/index/hero/loading.webp' %}" type="image/webp">
                        <img class="lazy" data-src="{% static 'img/index/hero/loading.png' %}" alt="" width="81"
                             height="81">
                    </picture>
                </div>
                <div class="hero__image--item">
                    <picture>
                        <source data-srcset="{% static 'img/index/hero/ethereum.webp' %}" type="image/webp">
                        <img class="lazy" data-src="{% static 'img/index/hero/ethereum.png' %}" alt="" width="150"
                             height="150">
                    </picture>
                </div>
                <div class="hero__image--item">
                    <picture>
                        <source data-srcset="{% static 'img/index/hero/hashtag.webp' %}" type="image/webp">
                        <img class="lazy" data-src="{% static 'img/index/hero/hashtag.png' %}" alt="" width="202"
                             height="202">
                    </picture>
                </div>
            </div>
        </section>

        {% include 'include/full_coin_table.html' with listing_page=True %}

    </main>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {

            $('#search-form input[name="q"]').on('keyup', function () {
                clearTimeout(typingTimer); // Сбрасываем предыдущий таймер

                var input = $(this).val();

                if (input.length > 0) {
                    typingTimer = setTimeout(function () {
                        $.ajax({
                            url: '{% url "core:sort_ajax" %}', // URL для обработки AJAX-запроса
                            type: 'GET',
                            data: {q: input},
                            dataType: 'json',
                            success: function (response) {
                                // Очищаем текущий список результатов
                                $('#coin-list').empty();

                                // Отображаем только первые три результата
                                for (var i = 0; i < 5 && i < response.length; i++) {
                                    var coin = response[i];

                                    // Добавляем элемент списка
                                    var listItem = '<li><a href="' + coin.url + '"><b>' + coin.name + '</b></a>' +
                                        '<button type="button" aria-label="paste">' +
                                        '<svg width="24" height="24" viewBox="0 0 24 24">' +
                                        '<use xlink:href="{% static "img/sprites.svg" %}#arrow-link"></use>' +
                                        '</svg>' +
                                        '</button></li>';

                                    $('#coin-list').append(listItem);
                                }
                            },
                            error: function (xhr, textStatus, errorThrown) {
                                console.log('AJAX Error: ' + errorThrown);
                            }
                        });
                    }, doneTypingInterval);
                }
            });
        });
    </script>
{% endblock %}

core/templates/privacy-police.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}
    <title>{{ page.title_seo }}</title>
{% endblock %}

{% block description %}
<meta name="description" content="{{ page.description_seo }}">
{% endblock %}

{% block head %}
    <meta property="og:title" content="{% if page.title %}{{ page.title|striptags|truncatechars:50 }}{% endif %}"/>
    <meta property="og:description"
          content="{% if page.description %}{{ page.description|striptags|truncatechars:160 }}{% endif %}"/>
    <meta property="og:image" content="{% if page.image_url %}{{ page.image_url.url }}{% endif %}"/>
    <meta property="og:image:width" content="1200"/>
    <meta property="og:image:height" content="630"/>
    <meta property="og:url" content="{{ request.build_absolute_uri }}"/>
    <meta property="og:site_name" content="CoinYoYo"/>
    <meta property="og:type" content="website"/>
    <meta name="twitter:card" content="summary_large_image"/>
    
    <!-- JSON-LD Structured Data for BreadcrumbList -->
    <script type="application/ld+json">
        {
          "@context": "https://schema.org",
          "@type": "BreadcrumbList",
          "itemListElement": [
            {
              "@type": "ListItem",
              "position": 1,
              "name": "{% trans 'Home' %}",
              "item": "{{ request.scheme }}://{{ request.get_host }}{% url 'core:index' %}"
            },
            {
              "@type": "ListItem",
              "position": 2,
              "name": "{% trans 'Privacy policy' %}",
              "item": "{{ request.build_absolute_uri }}"
            }
          ]
        }
    </script>
{% endblock %}

{% load static %}
{% block content %}

<style type="text/css">
    .text-section__container li::before {
        counter-increment: none !important;
        content: none !important;
    }
</style>

<main class="main">
    <section class="text-section">
        <div class="hero-banner container _min">
            <div class="hero-banner__bg">
                <picture class="hero__bg-picture-dark">
                    <source data-srcset="{% static 'img/index/hero/bg.webp' %}" type="image/webp"
                            media="(min-width: 550px)">
                    <source data-srcset="{% static 'img/index/hero/bg-mob-2.webp' %}" type="image/webp">
                    <img data-src="{% static 'img/index/hero/bg.png' %}" alt="" width="0" height="0" class="lazy">
                </picture>
                <picture class="hero__bg-picture-light">
                    <source data-srcset="{% static 'img/index/hero/bg-light.webp' %}" type="image/webp"
                            media="(min-width: 550px)">
                    <source data-srcset="{% static 'img/index/hero/bg-light.webp' %}" type="image/webp">
                    <img data-src="{% static 'img/index/hero/bg-light.png' %}" alt="" width="0" height="0" class="lazy">
                </picture>
            </div>
            <div class="hero-banner__header">
                <div class="hero-banner__page-address page-address">
                    <ul>
                        <li>
                            <a href="{% url 'core:index' %}">
                                {% trans "Home" %}
                            </a>
                        </li>
                        <li>
                            <svg width="16" height="16" viewBox="0 0 16 16">
                                <use xlink:href="{% static 'img/sprites.svg#arrow-next' %}"></use>
                            </svg>
                        </li>
                        <li>
                            <a href="#">
                                {{page.title_seo}}
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <h1 class="hero-banner__title title">
                {{ page.title|safe }}
            </h1>
        </div>
        <div class="text-section__container container">
            <p>
                {{ page.description|safe }}
            </p>
        </div>
    </section>
</main>

{% endblock %}