coinjojo/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/coin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include('allauth.urls')),

]

urlpatterns += i18n_patterns(
    path('', include('core.urls')),
    path('', include('user.urls')),
    path('', include('order.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path

from core import views
from core.views import *
from core.utils import *

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('index/<str:sort>/', Index.as_view(), name='index_sorted'),

    path('index/<str:sort_item>/<str:sort_status>/', Index.as_view(), name='index_sorted_item'),
    path('coin-list/<slug>/', coin_list, name='list_sorted_item'),
    path('vote-coin/', vote_coin, name='vote_coin'),

    path('advertising/', advertising, name='advertising'),

    path('add-coin/', AddCoin.as_view(), name='add-coin'),
    path('coin-page/<slug:slug>/', CoinDetail.as_view(), name='coin-page'),
    path('coin-list/<str:filter_by>/', NewlistingList.as_view(), name='coin-list'),
    path('page/<slug>/', page, name='page'),
    path('search/', SearchList.as_view(), name='search'),
    path('coin-category/<slug:slug>/', NewlistingListCategory.as_view(), name='coin-list-category'),
    path('coin-category/<str:sort_item>/<str:sort_status>/<str:slug>', NewlistingListCategory.as_view(), name='category_sorted_item'),
    path('coin-chain/<slug:slug>/', NewlistingListChain.as_view(), name='coin-list-chain'),
    path('coin-chain/<str:sort_item>/<str:sort_status>/<str:slug>', NewlistingListChain.as_view(), name='chain_sorted_item'),
    path('coin-type/<slug:slug>/', NewlistingListType.as_view(), name='coin-list-type'),
    path('coin-type/<str:sort_item>/<str:sort_status>/<str:slug>', NewlistingListType.as_view(), name='type_sorted_item'),
    path('custom_set_language/', custom_set_language, name='custom_set_language'),
    # path('add_like/<int:pk>/', increment_counter, name='add_like')2,

    path('coin-promoted/', NewlistingListPromote.as_view(), name='promote-coin'),
    path('coin-promoted/<str:sort_item>/<str:sort_status>/', NewlistingListPromote.as_view(), name='promote-sort'),

    path('captcha/', captcha_view, name='captcha'),#`1
    path('sort/', get_sort_status_promoted, name='sort'),
    path('sort-promote/', get_sort_status_promote, name='sort-promote'),
    path('sort-list/', get_sort_status_list, name='sort-list'),
    path('sort-profile/', get_sort_status_profile, name='sort-profile'),

    path('search-ajax/', search_coins_ajax, name='search_ajax'),
    path('sort-ajax/', sort_filter_pagination_ajax, name='sort_ajax'),
    path('get_coins_table/', get_coins_table, name='get_coins_table'),

    path('coin-price-history', coin_price_history, name='coin_price_history'),

]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
{% get_available_languages as languages %}
{% get_current_language as CURRENT_LANGUAGE_CODE %}
<html lang="{{ CURRENT_LANGUAGE_CODE }}">
<head>
    {% block title %}
        <title>{{ page.title_seo }}</title>
    {% endblock %}
    <link rel="canonical" href="{{ request.build_absolute_uri }}">
    <link rel="shortcut icon" href="{% static 'img/favicon.svg' %}">
    <link rel="stylesheet" href="" id="preloader-css">
    {% for lang_code, lang_name in languages %}
        {% if lang_code != CURRENT_LANGUAGE_CODE %}
            <link rel="alternate"
                  href="{{ request.scheme }}://{{ request.get_host }}/{{ lang_code }}/{{ request.path|slice:"4:" }}"
                  hreflang="{{ lang_code }}"/>
        {% endif %}
    {% endfor %}
    <link rel="alternate" href="{{ request.build_absolute_uri }}" hreflang="{{ CURRENT_LANGUAGE_CODE }}"/>
    <link rel="alternate" href="{{ request.scheme }}://{{ request.get_host }}/en/{{ request.path|slice:"4:" }}"
          hreflang="x-default"/>
    <script src="{% static 'js/preloader.min.js' %}"></script>
    {% block description %}
        <meta name="description" content="{{ page.description_seo }}">
    {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="application/ld+json">
        {
          "@context": "https://schema.org",
          "@type": "Organization",
          "name": "CoinYoYo",
          "alternateName": "CoinYoYo",
          "url": "https://coinyoyo.io/en/",
          "logo": "https://coinyoyo.io/static/img/logo.svg",
          "sameAs": "https://x.com/CoinYoYo_io",
          "email": "coinyoyo.io99@gmail.com"
        }
    </script>
    <style>

        .image-body {
            width: 100%;
            position: relative;
        }

        .image-body img {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            object-fit: cover;
        }

        .lazy {
            opacity: 0;
        }

        .lazy.loaded {
            opacity: 1;
        }

        @media (min-width: 992px) {
            .header__nav--list li ul {
                width: 160% !important;
            }
        }

        .table-coins__number::before {
            counter-increment: none !important;
            content: none !important;
            font-weight: 400
        }
    </style>
    {% block head %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style-critical.min.css' %}">
    <link rel="preload" href="{% static 'css/style.min.css' %}" as="style"
          onload="this.onload=null;this.rel='stylesheet'">
    <noscript>
        <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
    </noscript>
    <link rel="stylesheet" href="" id="theme-file" media="all">

    <script>
        var whiteThemeFileUrl = '{% static "css/light-mode.css" %}';
        var lightPreloaderUrl = '{% static "css/preloader-light.css" %}';
        var darkPreloaderUrl = '{% static "css/preloader-dark.css" %}';

        function updateThemeUrl() {
            if (localStorage.getItem('coinyoyo-theme') === 'dark') {
                document.getElementById('preloader-css').href = darkPreloaderUrl;
            } else {
                document.getElementById('preloader-css').href = lightPreloaderUrl;
                document.getElementById('theme-file').href = whiteThemeFileUrl;
            }
        }

        updateThemeUrl();
    </script>
    <script>
        document.querySelector('html').style.setProperty("--vh", window.innerHeight * 0.01 + "px");
    </script>

    <!-- Google Analytics 4 tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-LDRWKZNCKB"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'G-LDRWKZNCKB');
    </script>
</head>
<body>
<div class="wrapper" style="visibility: hidden; opacity: 0">
    {% include 'include/_header.html' %}

    {% block content %}

    {% endblock %}

    {% include 'include/_footer.html' %}
</div>
<div id="preloader" class="preloader">
    <img alt="Logo" class="logo-preloader">
</div>
</body>
{#<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>#}
<script>
    $(document).ready(function () {
        var typingTimer; // Таймер для задержки перед выполнением AJAX-запроса
        var doneTypingInterval = 300; // Задержка в миллисекундах

        $('#search-form input[name="q"]').on('keyup', function () {
            clearTimeout(typingTimer); // Сбрасываем предыдущий таймер

            var input = $(this).val();

            if (input.length > 0) {
                typingTimer = setTimeout(function () {
                    $.ajax({
                        url: '{% url "core:search_ajax" %}', // URL для обработки AJAX-запроса
                        type: 'GET',
                        data: {q: input},
                        dataType: 'json',
                        success: function (response) {
                            // Очищаем текущий список результатов
                            $('#coin-list').empty();

                            // Отображаем только первые три результата
                            for (var i = 0; i < 5 && i < response.length; i++) {
                                var coin = response[i];

                                // Добавляем элемент списка
                                var listItem = '<li><a href="' + coin.url + '"><b>' + coin.name + '</b></a>' +
                                    '<button type="button" aria-label="paste">' +
                                    '<svg width="24" height="24" viewBox="0 0 24 24">' +
                                    '<use xlink:href="{% static "img/sprites.svg" %}#arrow-link"></use>' +
                                    '</svg>' +
                                    '</button></li>';

                                $('#coin-list').append(listItem);
                            }
                        },
                        error: function (xhr, textStatus, errorThrown) {
                            console.log('AJAX Error: ' + errorThrown);
                        }
                    });
                }, doneTypingInterval);
            }
        });
    });
</script>
<script src="{% static 'js/libs.min.js' %}" defer></script>
<script src="{% static 'js/main.min.js' %}" defer></script>
<!-- <script src="{% static 'js/ajax.js' %}" defer></script> -->
{#<script src="https://www.google.com/recaptcha/api.js" async defer></script>#}
{% block scripts %}
{% endblock %}